export { default as Login } from './Login'
export { default as Home } from './Home'
export { default as Register } from './Register'
export { default as RestApi } from './RestApi'
export { default as AVView } from './AVView'
export { default as Chat } from './Chat'
export { default as Setting } from './Setting'
